executable            = condor_capid_checker.sh
#input                 = /cms/chiarito/work/hcal/CMSSW_10_1_1/test/capid_checker.py
#transfer_input_files  = HcalTupleMaker_new2_5k.root
arguments             = $(Process)
output                = condor_capid_checker_run316972/out_$(Cluster)_$(Process).txt
error                 = condor_capid_checker_run316972/out_$(Cluster)_$(Process).txt
log                   = condor_capid_checker_run316972/log_$(Cluster).txt
+JobFlavour = "longlunch"
Notification=never
queue 70

#transfer_input_files = $(filename)
#arguments            = $(filename) $(Process)
#initialdir           = /cms/chiarito/eos/hcal/task9/run316110_filebased/ZeroBias/hcaltuple_run316110/180719_085550/0000/
#queue filename matching files *.root
